x-laravel: &laravel
  env_file:
    - path: ./.env
      required: true

  build:
    context: .
    dockerfile: ./docker/Dockerfile.dev
    args:
      UID: ${DOCKER_UID:-1000}
      GID: ${DOCKER_GID:-1000}
      USER: ${DOCKER_USER:-mahdi}

  networks:
    - app-network

  volumes:
    - ./src:/var/www/html
    - ./python:/var/www/python
    - ./infra/php.ini:/usr/local/etc/php/php.ini

  extra_hosts:
    - "host.docker.internal:host-gateway"

  depends_on:
    postgres:
      condition: service_healthy
    redis:
      condition: service_healthy


services:

  php:
    <<: *laravel
    command: php-fpm
    container_name: trade-screener-php


  horizon:
    <<: *laravel
    container_name: trade-screener-horizon
    command: php artisan horizon

  postgres:
    image: postgres:17

    container_name: trade-screener-postgres

    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    volumes:
      - postgres-data:/var/lib/postgresql/data

    networks:
      - app-network

    restart: unless-stopped

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: trade-screener-redis

    volumes:
      - redis-data:/data

    networks:
      - app-network

    restart: unless-stopped

    command: redis-server --appendonly yes

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
    name: trade-screener-postgres-data

  redis-data:
    name: trade-screener-redis-data


networks:
  app-network:
    driver: bridge